#!/usr/bin/env bash
text="$(xsel -o)"
translate="$(wget -U "Mozilla/5.0" -qO - "http://localhost:3000/?a=es&texto=$(echo $text)")"
echo -e "Texto original:" "$text"'\n' > /tmp/notification
echo "Texto traducido:" "$translate" >> /tmp/notification
zenity --text-info --title="Traducción Ingles a español" --filename=/tmp/notification